use_frameworks!

platform :ios, '8.0'

target 'CSSDeviceInfoManager_Example' do
  pod 'CSSDeviceInfoManager', :path => '../'

  target 'CSSDeviceInfoManager_Tests' do
    inherit! :search_paths

    
  end
end
